<?php

/**
 * Implements hook_install().
 *
 * Perform actions to set up the webform feature.
 */
function campuscms_feature_webform_install() {
  if (module_exists('custom_breadcrumbs')) {
    _campuscms_feature_webform_custom_breadcrumbs();
  }
}

/**
 * Implements hook_uninstall().
 */
function campuscms_feature_webform_uninstall() {
  if (module_exists('custom_breadcrumbs')) {
    db_delete('custom_breadcrumbs')->condition('name', 'campuscms_feature_webform-%', 'LIKE')->execute();
  }
}
